#配置当前环境profile
spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #thymeleaf配置
  thymeleaf:
    enabled: true
    suffix: .html
    prefix: classpath:/templates/
    cache: false
#####公共配置#####
server:
  port: 8081

#日志配置
logging:
  level:
    root: INFO



